### ISSUE TITLE
pytest configuration in the setup.py collides with the pip development installation

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/VirES-Python-Client#50]
Tested in a development Vagrant CentOS 7 instance.

```
pip install -e /usr/local/viresclient
```
crashes with the following error

```
Obtaining file:///usr/local/viresclient
    ERROR: Command errored out with exit status 1:
     command: /var/www/vires/venv_p36_jhub/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/usr/local/viresclient/setup.py'"'"'; __file__='"'"'/usr/local/viresclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4091qfsn
         cwd: /usr/local/viresclient/
    Complete output (33 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/viresclient/setup.py", line 78, in <module>
        'viresclient=viresclient.commands.viresclient:start',
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 770, in resolve
        replace_conflicting=replace_conflicting
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1053, in best_match
        return self.obtain(req, installer)
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in obtain
        return installer(requirement)
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 678, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 704, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 854, in install_eggs
        return [self.install_wheel(dist_filename, tmpdir)]
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 1072, in install_wheel
        os.path.dirname(destination)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib64/python3.6/distutils/util.py", line 301, in execute
        func(*args)
      File "/var/www/vires/venv_p36_jhub/lib64/python3.6/site-packages/setuptools/wheel.py", line 135, in install_as_egg
        os.path.join(egg_info, 'PKG-INFO'))
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/viresclient/.eggs/pytest_runner-5.2-py3.6.egg/EGG-INFO/METADATA' -> '/usr/local/viresclient/.eggs/pytest_runner-5.2-py3.6.egg/EGG-INFO/PKG-INFO'
```

Removing following lines from the `setup.py` solves the problem
``` 
    setup_requires=['pytest-runner'],
    tests_require=['pytest'],
```

**Comment by smithara** [comment]
I've fixed this on `staging`... had to wrestle with pytest, coverage and Travis a bit (I'll need to look more into tox and other modernisations)

I am also taking the opportunity to drop python 3.5 support (in line with other upstream deprecation of 3.5). I'll make a new release soon together with the AEBS stuff
